// Behavioral PostgreSQL tests using an isolated PGlite database. This fixture
// contains the existing columns referenced by this migration, not a Supabase
// service emulator. Pass the installed PGlite module path as argv[2].
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
const { PGlite } = await import(process.argv[2] ? pathToFileURL(process.argv[2]).href : '@electric-sql/pglite');
const pg = new PGlite();
await pg.exec(`
create schema private; create schema auth;
create role anon; create role authenticated; create role service_role;
create function auth.role() returns text language sql as $$select current_setting('request.jwt.claim.role',true)$$;
create table public.weekly_quiz_rounds(round_id text primary key,campaign_id text,environment text,status text,opens_at timestamptz,closes_at timestamptz,opened_at timestamptz,revealed_at timestamptz,blind_manifest_sha256 text,metadata jsonb);
create table public.prerelease_snapshots(campaign_id text,release_date date);
create table public.targets(target_id text primary key,campaign_id text);
create table public.prediction_runs(run_id text primary key,target_id text,status text,attempt_count int);
create table private.weekly_selector_kit_catalog(round_id text,kit_sha256 text,blind_manifest_sha256 text,storage_path text,descriptor jsonb);
create table private.weekly_featured_question_selections(round_id text,blind_manifest_sha256 text);
create table public.weekly_quiz_evaluations(round_id text,round_closes_at timestamptz,blind_manifest_sha256 text,evaluation_id text,campaign_id text,environment text,round_opens_at timestamptz,private_index_sha256 text,reveal_manifest_sha256 text);
create function public.reveal_weekly_quiz_round(text,jsonb,text) returns void language sql as $$update public.weekly_quiz_rounds set status='revealed',revealed_at=clock_timestamp() where round_id=$1$$;
create table public.weekly_retrospective_publications(round_id text);
create table public.weekly_selector_post_close_benchmarks_v1(execution_id uuid,round_id text,environment text,execution_sha256 text,payload_digest text,provider text,requested_model_id text,config_sha256 text,execution jsonb);
`);
await pg.exec(fs.readFileSync(new URL('../../supabase/migrations/20261004090000_add_weekly_automation_outbox.sql', import.meta.url), 'utf8'));
const rpc = async (name, args=[]) => (await pg.query(`select public.${name}(${args.map((_, i) => `$${i+1}`).join(',')}) as value`, args)).rows[0].value;
await assert.rejects(rpc('weekly_automation_snapshot_v1'), /service role/);
await pg.exec(`set request.jwt.claim.role='service_role'`);
assert.deepEqual(await rpc('weekly_automation_snapshot_v1'), {rounds:[],campaigns:[],failed_actions:[],action_history:{}});
const key = 'a'.repeat(64);
const action = { action_key:key,kind:'reveal',identity:'round1',parameters:{round_id:'round1'},gate:'reveal' };
assert.equal((await rpc('enqueue_weekly_automation_action_v1',[action])).status, 'pending');
await rpc('enqueue_weekly_automation_action_v1',[action]);
await assert.rejects(rpc('enqueue_weekly_automation_action_v1',[{...action,identity:'wrong'}]), /bound differently/);
let claim = await rpc('claim_weekly_automation_action_v1',[key]);
assert.equal(claim.attempt_count,1);
assert.equal(await rpc('claim_weekly_automation_action_v1',[key]),null);
await assert.rejects(rpc('finish_weekly_automation_action_v1',[key,'00000000-0000-4000-8000-000000000001','succeeded',null]), /stale automation lease/);
assert.equal((await rpc('finish_weekly_automation_action_v1',[key,claim.lease_token,'waiting',null])).attempt_count,0);
assert.equal(await rpc('claim_weekly_automation_action_v1',[key]),null);
await pg.query(`update private.weekly_automation_actions set next_attempt_at=clock_timestamp()-interval '1 second' where action_key=$1`,[key]);
claim = await rpc('claim_weekly_automation_action_v1',[key]);
const oldLease = claim.lease_token;
await pg.query(`update private.weekly_automation_actions set lease_until=clock_timestamp()-interval '1 second' where action_key=$1`,[key]);
claim = await rpc('claim_weekly_automation_action_v1',[key]);
assert.notEqual(claim.lease_token,oldLease);
assert.equal(claim.attempt_count,2);
await assert.rejects(rpc('finish_weekly_automation_action_v1',[key,oldLease,'succeeded',null]), /stale automation lease/);
for (let attempt=2;attempt<=5;attempt++) {
  const done=await rpc('finish_weekly_automation_action_v1',[key,claim.lease_token,'error','RuntimeError']);
  assert.equal(done.status,attempt===5?'failed':'pending');
  await pg.query(`update private.weekly_automation_actions set next_attempt_at=clock_timestamp()-interval '1 second' where action_key=$1`,[key]);
  claim=await rpc('claim_weekly_automation_action_v1',[key]);
}
assert.equal(claim,null);
assert.equal((await rpc('weekly_automation_snapshot_v1')).failed_actions.length,1);
const digest='b'.repeat(64);
await pg.query(`insert into public.weekly_quiz_rounds values('round1','wwpdb-2026-09-05','production','open','2026-09-05T03:00Z','2026-09-23T00:00Z','2026-09-05T03:00Z',null,$1,'{}')`,[digest]);
const job={execution_id:'00000000-0000-4000-8000-000000000001',driver:'claude',model_id:'exact-model',config_sha256:'c'.repeat(64)};
assert.equal((await rpc('freeze_weekly_automation_policy_v1',['round1',[job]])).idempotent,false);
assert.equal((await rpc('freeze_weekly_automation_policy_v1',['round1',[job]])).idempotent,true);
await assert.rejects(rpc('freeze_weekly_automation_policy_v1',['round1',[]]), /immutable/);
await assert.rejects(rpc('freeze_weekly_automation_policy_v1',['round1',[{...job,driver:'wrong'}]]), /immutable/);
const uri='supabase://private-bucket/sha256/dd/'+'d'.repeat(64);
await rpc('register_weekly_automation_artifact_v1',[job.execution_id,uri,'d'.repeat(64)]);
await rpc('register_weekly_automation_artifact_v1',[job.execution_id,uri,'d'.repeat(64)]);
await assert.rejects(rpc('register_weekly_automation_artifact_v1',[job.execution_id,uri,'e'.repeat(64)]), /immutable/);
await pg.query(`insert into public.weekly_quiz_evaluations(round_id,round_closes_at,blind_manifest_sha256) values('round1','2026-09-16T00:00Z',$1)`,[digest]);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].evaluation_ready,false);
await pg.exec(`update public.weekly_quiz_evaluations set round_closes_at='2026-09-23T00:00Z'`);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].evaluation_ready,false);
await pg.query(`insert into public.weekly_selector_post_close_benchmarks_v1 values($1,'round1','production',$2,$2,'wrong','exact-model',$3,$4)`,[job.execution_id,'e'.repeat(64),job.config_sha256,{blind_manifest_sha256:digest}]);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].benchmark_jobs[0].receipt,null);
await pg.exec(`update public.weekly_selector_post_close_benchmarks_v1 set provider='claude'`);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].benchmark_jobs[0].receipt,null);
await assert.rejects(rpc('verify_weekly_automation_benchmark_v1',[job.execution_id,'e'.repeat(64),'e'.repeat(64),'e'.repeat(64)]),/artifact binding differs/);
await rpc('verify_weekly_automation_benchmark_v1',[job.execution_id,'d'.repeat(64),'e'.repeat(64),'e'.repeat(64)]);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].benchmark_jobs[0].receipt.execution_id,job.execution_id);
await pg.query(`update public.weekly_quiz_evaluations set evaluation_id='eval1',campaign_id='wwpdb-2026-09-05',environment='production',round_opens_at='2026-09-05T03:00Z',private_index_sha256=$1,reveal_manifest_sha256=$1`,['f'.repeat(64)]);
await pg.query(`update public.weekly_quiz_rounds set metadata=$1`,[{private_index:{sha256:'f'.repeat(64)}}]);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].evaluation_ready,true);
await pg.exec(`update public.weekly_quiz_evaluations set round_opens_at='2026-09-06T03:00Z'`);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].evaluation_ready,false);
await pg.exec(`update public.weekly_quiz_evaluations set round_opens_at='2026-09-05T03:00Z',private_index_sha256='wrong'`);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].evaluation_ready,false);
await pg.query(`update public.weekly_quiz_evaluations set private_index_sha256=$1`,['f'.repeat(64)]);
await pg.exec(`update public.weekly_quiz_rounds set closes_at='2026-09-24T00:00Z'`);
await assert.rejects(rpc('reveal_weekly_automation_round_v1',['round1','eval1',{},'f'.repeat(64)]),/window binding mismatch/);
await pg.exec(`update public.weekly_quiz_rounds set closes_at='2026-09-23T00:00Z'`);
assert.equal((await rpc('reveal_weekly_automation_round_v1',['round1','eval1',{},'f'.repeat(64)])).status,'revealed');
await pg.exec(`set role anon; set request.jwt.claim.role='anon'`);
await assert.rejects(rpc('weekly_automation_snapshot_v1'), /permission denied/);
await assert.rejects(pg.query('select * from private.weekly_automation_actions'), /permission denied/);
await pg.exec(`reset role; set role authenticated; set request.jwt.claim.role='authenticated'`);
await assert.rejects(rpc('claim_weekly_automation_action_v1',[key]), /permission denied/);
await pg.exec(`reset role; set role service_role; set request.jwt.claim.role='service_role'`);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds.length,1);
await assert.rejects(pg.query('update private.weekly_automation_actions set status=\'succeeded\''), /permission denied/);
await pg.close();
console.log('Weekly automation PostgreSQL behavior: leases, bounded retry, frozen expectations, artifact immutability, exact state, and service-only privileges passed.');
