// Isolated real PostgreSQL migration behavior; pass PGlite module and Python fixture.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.argv[2]).href);
const pg=new PGlite();
const base=fs.readFileSync(new URL('./check_weekly_automation_database.mjs',import.meta.url),'utf8');
await pg.exec(base.split('await pg.exec(`')[1].split('`);')[0]);
await pg.exec(`alter table public.weekly_quiz_rounds add blind_manifest jsonb, add reveal_manifest jsonb;
create schema extensions;
create function extensions.digest(bytea,text) returns bytea language sql immutable as $$select sha256($1)$$;`);
await pg.exec(fs.readFileSync(new URL('../../supabase/migrations/20261004090000_add_weekly_automation_outbox.sql',import.meta.url),'utf8'));
await pg.exec(fs.readFileSync(new URL('../../supabase/migrations/20261004210000_historical_preview_research_archive.sql',import.meta.url),'utf8'));
const f=JSON.parse(fs.readFileSync(process.argv[3])); const r=f.round;
const rpc=async(name,args=[])=>(await pg.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as value`,args)).rows[0].value;
await pg.query(`insert into public.weekly_quiz_rounds(round_id,campaign_id,environment,status,opens_at,closes_at,blind_manifest_sha256,metadata,blind_manifest) values($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[r.round_id,r.campaign_id,r.environment,r.status,r.opens_at,r.closes_at,r.blind_manifest_sha256,r.metadata,r.blind_manifest]);
const authArgs=[r.round_id,r.blind_manifest_sha256,r.metadata.private_index.sha256,r.opens_at,r.closes_at];
await assert.rejects(rpc('authorize_weekly_historical_preview_v1',authArgs),/service role/);
await pg.exec(`set request.jwt.claim.role='service_role'`);
await assert.rejects(rpc('authorize_weekly_historical_preview_v1',[...authArgs.slice(0,4),'2026-08-18T20:00:00Z']),/exact original/);
const scope=await rpc('authorize_weekly_historical_preview_v1',authArgs);
assert.deepEqual(scope,await rpc('authorize_weekly_historical_preview_v1',authArgs));
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].historical_scope.scope_id,scope.scope_id);
await assert.rejects(pg.exec(`update private.weekly_historical_preview_scopes set campaign_id='other'`),/immutable/);
await assert.rejects(rpc('register_weekly_historical_evaluation_v1',[r.round_id,{...f.descriptor,item_count:null}]),/differs/);
await rpc('register_weekly_historical_evaluation_v1',[r.round_id,f.descriptor]);
assert.deepEqual(await rpc('register_weekly_historical_evaluation_v1',[r.round_id,f.descriptor]),f.descriptor);
await assert.rejects(rpc('register_weekly_historical_evaluation_v1',[r.round_id,{...f.descriptor,evaluation_id:'different'}]),/bound differently/);
await pg.exec(`update public.weekly_quiz_rounds set opens_at=opens_at+interval '1 second'`);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].historical_evaluation_ready,false);
await assert.rejects(rpc('register_weekly_historical_evaluation_v1',[r.round_id,f.descriptor]),/source changed/);
await pg.query('update public.weekly_quiz_rounds set opens_at=$1',[r.opens_at]);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].historical_evaluation_ready,true);
f.public.source={...f.public.source,scope_id:scope.scope_id,opens_at:scope.opens_at,closes_at:scope.closes_at};
const publish=async a=>{const text=JSON.stringify(a),sha=createHash('sha256').update(text).digest('hex');return rpc('publish_weekly_historical_preview_v1',[r.round_id,text,`supabase://prediction-results/sha256/${sha.slice(0,2)}/${sha}`]);};
await assert.rejects(publish(f.public),/no rows/);
if(process.argv.includes('--benchmark')) {
 const id='00000000-0000-4000-8000-000000000003',config='c'.repeat(64),semantic='d'.repeat(64),payload='e'.repeat(64),file='f'.repeat(64);
 const job={execution_id:id,driver:'cursor',model_id:'exact-model',config_sha256:config};
 await rpc('freeze_weekly_automation_policy_v1',[r.round_id,[job]]);
 await assert.rejects(publish(f.public),/every frozen verified receipt/);
 await rpc('register_weekly_automation_artifact_v1',[id,`supabase://prediction-results/sha256/ff/${file}`,file]);
 const decisions=f.public.items.map(i=>({item_id:i.id,clustered:{selection_kind:'none'},unclustered:{selection_kind:'none'},clustered_correct:i.evaluation_status==='unscorable'?null:false,unclustered_correct:i.evaluation_status==='unscorable'?null:false}));
 const execution={blind_manifest_sha256:r.blind_manifest_sha256,payload:{items:decisions.map(({item_id,clustered,unclustered})=>({item_id,clustered,unclustered}))}};
 await pg.query(`insert into public.weekly_selector_post_close_benchmarks_v1 values($1,$2,'preview',$3,$4,'cursor','exact-model',$5,$6)`,[id,r.round_id,semantic,payload,config,execution]);
 await assert.rejects(publish(f.public),/every frozen verified receipt/);
 await rpc('verify_weekly_automation_benchmark_v1',[id,file,semantic,payload]);
 f.public.benchmarks=[{execution_id:id,driver:'cursor',model_id:'exact-model',config_sha256:config,execution_sha256:semantic,payload_digest:payload,decisions}];
 const wrong=structuredClone(f.public);wrong.benchmarks[0].execution_sha256='a'.repeat(64);
 await assert.rejects(publish(wrong),/receipt differs/);
 const wrongDecision=structuredClone(f.public);wrongDecision.benchmarks[0].decisions[0].unclustered={selection_kind:'choice',choice_id:'fabricated'};
 await assert.rejects(publish(wrongDecision),/decision differs/);
} else await rpc('freeze_weekly_automation_policy_v1',[r.round_id,[]]);
await assert.rejects(publish({...f.public,human_cohort:{included:true}}),/identity or cohort/);
const wrong=structuredClone(f.public);wrong.items[0].choices.pop();await assert.rejects(publish(wrong),/population/);
const unsafe=structuredClone(f.public);unsafe.items[0].user_id='person';await assert.rejects(publish(unsafe),/schema/);
assert.equal((await pg.query('select * from public.public_weekly_historical_preview_research')).rows.length,0);
const publication=await publish(f.public);assert.deepEqual(await publish(f.public),publication);
assert.equal((await rpc('weekly_automation_snapshot_v1')).rounds[0].historical_published,true);
await assert.rejects(pg.exec('delete from private.weekly_historical_preview_publications'),/immutable/);
await pg.exec(`set role anon; set request.jwt.claim.role='anon'`);
await assert.rejects(rpc('get_weekly_historical_preview_v1',[r.round_id]),/permission denied/);
const summaries=(await pg.query('select * from public.public_weekly_historical_preview_research')).rows;
assert.equal(summaries.length,1);assert.equal(summaries[0].human_votes_included,false);assert.equal('public_artifact_object_uri' in summaries[0],false);
await pg.exec('reset role');
await pg.exec(`update public.weekly_quiz_rounds set closes_at=closes_at+interval '1 second'`);
assert.equal((await pg.query('select * from public.public_weekly_historical_preview_research')).rows.length,0);
await pg.close();console.log('Historical Preview SQL: exact immutable source, private evaluation, closed original window, frozen receipt policy, full population, no human cohort, atomic publication and service-only mutations passed.');
